//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StackOverFIME_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CommentaryId { get; set; }
        public string Text { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Commentary Commentary { get; set; }
    }
}
